config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[new create show]
  get 'sessions/new', to: 'sessions#new' 
  post 'sessions', to: 'sessions#create'
  delete 'sessions', to: 'sessions#destroy'
  # EventsController routes
  resources :events, only: [:new, :create, :show, :index]
  root to: 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :event_attendees, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendees

  scope :past, -> { Event.all.select { |event| event.date < Date.today } }
  scope :upcoming, -> { Event.all.select { |event| event.date >= Date.today } }
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :creator_id
  has_many :event_attendees, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = User.find(session[:user_id]).events.build(event_params) unless session[:user_id].nil?
    redirect_to events_path if @event.save
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:description, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    session[:user_id] = User.find_by(name: params[:name]).id
    redirect_to new_user_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to sessions_new_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  # No method error for #create. Therefore, @user is currently nil.

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
      flash[:success] = 'User creation unsuccessful.'
    else
      flash.now[:alert] = 'User creation unsuccessful.'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(url: './', model: @event, action: 'post') do |f| %>
  <%= f.text_area :description %></br>
  <%= f.date_field :date %></br>
  <%= f.submit %>
<% end %>

app/views/events/index.html.erb
<div>
  <h3>Past Events</h3>
  <ul>
    <% Event.past.each do |event| %>
      <li><%= event.description %></li>
    <% end %>
  </ul>
</div>

<div>
  <h3>Upcoming Events</h3>
  <ul>
    <% Event.upcoming.each do |event| %>
      <li><%= event.description %></li>
    <% end %>
  </ul>
</div>

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/show.html.erb
<h6>
  <%= @event.creator.name %>
</h6>

<div>
  <h5>Attendees</h5>
  <ul>
    <% @event.attendees.each do |attendee| %>
      <li>
        <%= attendee.name %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar">
      <ul>
        <% unless session[:user_id].nil? %>
        <li>
          <%= link_to "Create a new event", new_event_path %>
        </li>
        <% end %>

        <% unless session[:user_id].nil? %>
        <li>
          <%= link_to "View all events", events_path  %>
        </li>
        <% end %>
        
        <% unless session[:user_id].nil? %>
          <li><%= link_to "View your events", user_path(session[:user_id])  %></li>
        <% end %>

        <% if session[:user_id].nil? %>
          <li><%= link_to "Sign Up", new_user_path %></li>
        <% end %>

        <li>
          <% if session[:user_id].nil? %>
            <%= link_to "Log In", { controller: "sessions", action: "new" } %>
          <% else %>
            <%= link_to "Log Out", "/sessions", { method: 'delete' } %>
          <% end %>
        </li>

      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<h1>Sign Up Form</h1>

<%= form_with(model: @user, url: users_path, method: 'post') do |f| %>
  <%= f.label :name, "Username"  %>
  <%= f.text_field :name %>
  <%= f.submit "Submit" %>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h1>
  <%= "This is a list of all #{@user.name}'s Events" %>
</h1>

<div>
  <h6>Created Events</h6>
  <ul>
    <% @user.events.each do |event| %>
      <li><%= event.description%></li>
    <% end %>
  </ul>
</div>

<div>
  <h6>Previously Attended Events</h6>
  <ul>
    <% @user.attended_events.each do |event| %>
      <% if event.date < Date.today %>
        <li><%= event.description %></li>
      <% end %>
    <% end %>
  </ul>
</div>

<div>
  <h6>Upcoming Events</h6>
  <ul>
    <% @user.attended_events.each do |event| %>
      <% if event.date >= Date.today %>
        <li><%= event.description %></li>
      <% end %>
    <% end %>
  </ul>
</div>